import React, {useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import './style.css';
const API='/api/v1';
async function read(path){const response=await fetch(API+path);if(!response.ok)throw Error(`${response.status} ${path}`);return response.json()}
async function send(path,body={}){const response=await fetch(API+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw Error(data.detail||response.statusText);return data}
function Pill({children,tone=''}){return <span className={'pill '+tone}>{children}</span>}
function Section({label,title,children,action}){return <section className="panel"><div className="section-head"><div><span className="eyebrow">{label}</span><h2>{title}</h2></div>{action}</div>{children}</section>}
function App(){
  const [data,setData]=useState({});const [error,setError]=useState('');const [notice,setNotice]=useState('');const [query,setQuery]=useState('red status beacon pump');const [context,setContext]=useState('zone_01');const [hits,setHits]=useState(null);const [busy,setBusy]=useState(false);const [tick,setTick]=useState(0);const [offline,setOffline]=useState(false);
  async function refresh(){const names=['engine/status','sync/status','telemetry/detector','perception/status','events?limit=30','network/status','conflicts'];const results=await Promise.allSettled(names.map(read));setData(old=>{let next={...old};names.forEach((name,i)=>{if(results[i].status==='fulfilled')next[name.split('?')[0]]=results[i].value});return next});const networkResult=results[names.indexOf('network/status')];if(networkResult.status==='fulfilled')setOffline(networkResult.value.is_offline);setTick(Date.now())}
  useEffect(()=>{refresh();const timer=setInterval(refresh,1800);return()=>clearInterval(timer)},[]);
  async function act(path,body={},message='Done'){setBusy(true);setError('');try{await send(path,body);setNotice(message);await refresh()}catch(e){setError(String(e.message))}finally{setBusy(false)}}
  async function search(e){e?.preventDefault();setBusy(true);setError('');try{setHits(await send('/search/text',{text:query,context,k:5}))}catch(e){setError(String(e.message))}finally{setBusy(false)}}
  const engine=data['engine/status']||{}, sync=data['sync/status']||{},telemetry=data['telemetry/detector']||{},perception=data['perception/status']||{},events=data.events?.events||[],network=data['network/status']||{},conflicts=data.conflicts?.conflicts||[];
  const memory=Math.round((engine.usage_bytes||0)/1048576), budget=Math.round((engine.soft_budget_bytes||0)/1048576),memPct=budget?Math.min(100,100*memory/budget):0;
  return <div className="shell"><aside><div className="brand"><span className="mark">✳</span><div><strong>LIFELINE</strong><small>EDGE COMMAND</small></div></div><div className="side-label">DEVICE / 01</div><nav><a href="#overview" className="selected">◉ <span>Overview</span></a><a href="#search">⌕ <span>Memory search</span></a><a href="#shards">▦ <span>Shard inspector</span></a><a href="#sync">↗ <span>Sync & privacy</span></a><a href="#timeline">≋ <span>Activity</span></a></nav><div className="side-bottom"><div className="status-dot"/> EDGE RUNTIME <Pill tone="green">LOCAL</Pill><p>Offline-first inspection memory<br/>Demo fixture · non-operational</p></div></aside>
  <main id="overview"><header><div><span className="eyebrow">INSPECTION SYSTEM / ZONE 01</span><h1>Device overview<span className="period">.</span></h1><p>Detector, memory and transport state in one place.</p></div><div className="top-actions"><Pill tone={offline?'amber':'green'}>{offline?'LINK INTERRUPTED':'LINK CONFIGURED'}</Pill><button onClick={()=>act('/demo/seed',{},'Demo memory seeded')} disabled={busy}>Seed demo data</button></div></header>
  {error&&<div className="banner error" role="alert">{error}<button onClick={()=>setError('')}>×</button></div>}{notice&&<div className="banner">{notice}<button onClick={()=>setNotice('')}>×</button></div>}
  <div className="stat-grid"><div className="stat"><span>PROCESSED FPS</span><strong>{telemetry.fps??'—'}</strong><small>{telemetry.provenance||'Waiting for frames'}</small></div><div className="stat"><span>P95 FRAME LATENCY</span><strong>{telemetry.p95_latency_ms??'—'}<em> ms</em></strong><small>Actual processing time</small></div><div className="stat"><span>EDGE MEMORY</span><strong>{memory}<em> / {budget} MB</em></strong><div className="meter"><i style={{width:memPct+'%'}}/></div></div><div className="stat"><span>UPLOAD OUTBOX</span><strong>{sync.outbox_queued??'—'}</strong><small>{sync.urgent_queued??0} urgent queued</small></div></div>
  <div className="two"><Section label="01 / PERCEPTION" title="Live device" action={<Pill tone="amber">{perception.synthetic_input?'SYNTHETIC VIDEO':'NO VIDEO'}</Pill>}><div className="video">{perception.running?<img src={`${API}/perception/frame?t=${tick}`} alt="Synthetic inspection video with detector overlay"/>:<div className="empty">Start with LIFELINE_DEMO=1 for the synthetic inspection fixture.</div>}</div><div className="split-foot"><span>OpenCV red-beacon detector<br/><b>{perception.processed_frames||0}</b> frames processed</span><span>Frame queue <b>{telemetry.queue_depth??0}</b><br/>Dropped <b>{telemetry.dropped_frames??0}</b></span></div>{perception.latest_observation&&<div className="callout">Latest observation <code>{perception.latest_observation.record_id}</code> · {perception.latest_observation.projection_status}</div>}</Section>
  <Section label="02 / CONTROL" title="Operating state"><div className="control-row"><div><strong>Server link</strong><small>Pause client transport for a deterministic fault test.</small></div><button onClick={()=>act('/network/offline',{offline:!offline},!offline?'Client transport blocked':'Client transport restored')} disabled={busy}>{offline?'Restore link':'Interrupt link'}</button></div><div className="control-row"><div><strong>Outbox transfer</strong><small>Prioritize permitted urgent records.</small></div><button onClick={()=>act('/sync/trigger',{},'Sync triggered')} disabled={busy}>Sync now</button></div><div className="control-row"><div><strong>Indexed update</strong><small>Fetch a server-prepared shard for this context.</small></div><button onClick={()=>act('/snapshots/fetch',{context_id:context},'Snapshot activation requested')} disabled={busy}>Fetch snapshot</button></div><div className="info">This demo control injects a client failure. For a real outage, disconnect the Docker sync network.</div></Section></div>
  <div className="two" id="search"><Section label="03 / RETRIEVAL" title="Search local memory"><form onSubmit={search} className="search-form"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search incident history or procedures"/><select value={context} onChange={e=>setContext(e.target.value)}><option>zone_01</option><option>zone_02</option><option>emergency_protocols</option></select><button disabled={busy||!query.trim()}>Search</button></form>{hits&&<><div className="coverage">{['searched','queued','unavailable_offline','skipped_for_budget','failed'].map(key=><span key={key}><b>{key.replaceAll('_',' ')}</b> {hits.coverage?.[key]?.join(', ')||'—'}</span>)}</div>{hits.partial&&<div className="callout">Partial result · {hits.shortfall} fewer than requested</div>}{hits.hits?.length?<div className="results">{hits.hits.map((h,i)=><article key={i}><div><Pill tone={h.is_contested?'amber':'green'}>{h.status}</Pill><small>v{h.version} · {h.source_shard} · {Number(h.score).toFixed(3)}</small></div><strong>{h.entity_id}</strong><p>{JSON.stringify(h.observation)}</p></article>)}</div>:<div className="empty">No eligible matches in searched shards.</div>}</>}</Section>
  <Section label="04 / STORAGE" title="Shard inspector" action={<Pill>{context}</Pill>}><div id="shards" className="shards">{(engine.pinned||[]).map(id=><div key={id}><span className="tiny-dot green"/><strong>{id}</strong><Pill>PINNED</Pill></div>)}{(engine.loaded||[]).filter(id=>!(engine.pinned||[]).includes(id)).map(id=><div key={id}><span className="tiny-dot"/><strong>{id}</strong><Pill tone="green">ACTIVE</Pill></div>)}{!engine.loaded?.length&&<div className="empty">Waiting for engine status.</div>}</div><div className="split-foot"><span>Queued searches <b>{engine.queue_depth??0}</b></span><span>Projected records <b>{engine.projected_records_count??0}</b></span></div></Section></div>
  <div className="two" id="sync"><Section label="05 / TRANSFER" title="Sync & privacy"><div className="mini-grid"><div><span>Queued</span><strong>{sync.outbox_queued??0}</strong></div><div><span>Sent</span><strong>{sync.outbox_sent??0}</strong></div><div><span>Acknowledged</span><strong>{sync.outbox_acknowledged??0}</strong></div><div><span>Projection backlog</span><strong>{sync.projection_backlog??0}</strong></div></div><div className="info">Local-only records remain on the device; urgent priority never overrides sharing permission.</div></Section>
  <Section label="06 / REVIEW" title="Conflicts"><div className="results">{conflicts.length?conflicts.map((c,i)=><article key={i}><Pill tone="amber">CONTESTED</Pill><strong>{c.record_id}</strong><p>Operation {c.operation_id} · parent v{c.parent_version}</p></article>):<div className="empty">No contested revisions awaiting review.</div>}</div></Section></div>
  <Section label="07 / HISTORY" title="Activity timeline"><div id="timeline" className="timeline">{events.length?events.slice().reverse().map((e,i)=><div key={e.event_id||i}><span className="tiny-dot"/><time>{new Date(e.emitted_at).toLocaleTimeString()}</time><strong>{e.event_type}</strong><small>{e.component}</small></div>):<div className="empty">Events will appear as the device runs.</div>}</div></Section>
  <footer>LIFELINE / inspection demonstration · Synthetic procedures are not operational instructions.</footer></main></div>
}

createRoot(document.getElementById('root')).render(<App/>);
